## Python as a calculator

At its most basic Python can be used as a calculator, performing basic mathematical operations, such as:

In [1]:
4+8
217.81 * 3
18 * ( 29182 - 9382)
-305.8 / 21.1

-14.492890995260662

etc. Note that the spacing between the numbers and the operators does not matter to the Python interpreter; however, it is important to make the code readable to humans, so one should try to be consistent in form.

Mathematical order of operations is maintained within the context of evaluating expressions within parentheses first, and also evaluating multiplication and division before addition and subtraction. However, the Python interpreter may not necessarily evaluate a set of multiplications/divisions from left to right. We will see why this might matter shortly.

Python comes with many basic operations that we might expect: +, -, /, *, as well as parentheses (...). Additional operators include:

raising to a power with **, so that 5**2 raises squares five, returning 25; fractional and negative powers may be used
taking the modulus (i.e., finding the remainder of division) with %, so that 5 % 3 returns the remainder of dividing five by three, returning 2.
Think about the results of each of the following, and then evaluate in Python:

In [2]:
3**2
-3**2
10**5
9**0.5
4**(-0.5)
5 % 2
25 % 5
5 % 25

5

Consider the result of simple division: 2.0/3.0. What is the result? Well, in mathematics it would be 0.66666666… with an infinite number of decimal places. However, the computer has finite disk space and finite memory. In general, we cannot expect the computer to have an exact representation of such numbers, nor of irrational $(\sqrt{2}, 7^{1/3})$ and transcendental numbers ($\pi$, Euler’s e, etc.).

## Assignment and variables

The calculator functionality described above is useful at times, but it is not really programming, since we cannot combine results of different calculations and build on previous results, as values aren’t saved.

We now take a large step toward real programming by introducing Python’s assignment operator “=”. Thus, with:

In [3]:
# we will have the result of a calculation (12) stored, which we can access any time later by referring to x. For example:
x = 4 + 8

In [4]:
x = 4 + 8
y = 10**3
z = x*x - 10*y

The “=” in this context does not express mathematical equivalence (a passive statement that is true or false, just expressing equality). We cannot treat it like an alebraic expression and try rearrange the left hand side (LHS) and right hand side (RHS) to be something like:

In [ ]:
x - 4 = 8

or anything like that (try it, Python will produce an error).

This operator “=” is an action, providing a reference label to a value that is stored on the computer. In line with this concept, one can read it more like “x is defined to be …”, or “x is set to ….”, or “Let x be …”, etc. As such, every quantity on the RHS must be known and have a value already. Therefore, if c has not been assigned a value previously, then:

In [ ]:
d = c*c - 10
c = 4 + 8
# will produce an error when evaluating the first line. Consider the expression:

This is not a general relation, like the formula for a straight line in mathematics. This is a single instance, and a specific value for “x” must have been defined previously. (The way to write a general relation like the equation of a line is done by defining a function, discussed later).

There is a careful ordering to how Python treats lines with the assignment operator:

evaluate the RHS (if any term there has not been previously defined, an error occurs)
store the resulting value at some location on the computer (in an appropriate-sized space, based on the final type)
take the label the LHS and associate it with that location, so whenever that label occurs in an expression, Python will go the correct location and get the desired value.
The variable on the LHS of the assignment operator is, well, variable, and its value (and/or type, in Python) can be changed simply by assigning it to a new value at some point. So, at the end of these lines:

In [7]:
x = 10
x = -11.4
x = False

there is still only one variable x, and it refers to a quantity of type “bool” and value “False”.

The Python command _whos_ is a useful way to see what variables have been defined in a Python environment. It provides a list of the variable names, their values, their type and other properties.

## Variable names

There are some rules for variable names to keep in mind:

1. They must be made up only of alphanumeric characters (a-z, A-Z, 0-9) and the underscore character _.
2. The variable cannot start with a number, but the number may appear anywhere else.
3. Unusable characters: Special character such as \, $, %, !, etc. cannot* be used, nor can commas ,, periods . or dashes -, as those all have special other meanings. Spaces `` `` cannot be used, as those separate different words.
4. A variable name cannot be a reserved word or a key word (such as for, if, def, etc.). It also should not be word with special meaning (int, True, type, etc.) because the functionality of those original meanings should be maintained.
5. Variables are case sensitive (indeed, all words in Python are). That is, Python distinguishes between upper and lower case, so that Age, age and aGe are three different variables.
Please do remember to make meaningful variable names. For example, we emphasize here translating mathematics/physics/etc. from paper calculations to programs. Therefore, you should employ the same variable names and notations that you have written down to the program you are writing. For example, if writing the formula “distance equals velocity times time”, you should probably make use of the standard variables:

In [ ]:
d = v * t
# or perhaps more interpretable, but succinct, names:
dist = vel * time

Half (or more!) of the art of programming is to make the code itself as readable and understandable as possible. This makes the program simpler to check by eye while writing and more directly editable at future times. It also greatly reduces the numbers of bugs or errors in the code.

## Python Variables - Assign Multiple Values
Python allows you to assign values to multiple variables in one line:

In [29]:
x, y, z = "cat", "dog", "cow"
print(x)
print(y)
print(z)

cat
dog
cow

In [27]:
# You can't assign more values than the variables you have
a ,b = 4, 7, 3

ValueError: too many values to unpack (expected 2)

In [30]:
#Printing many variables in one sent using comma separator
print(x, y,z)

cat dog cow

In [33]:
#Printing using + symbol
print(x + " " + y + " " + z)

cat dog cow

In [35]:
#Age of animals
d, f, g, t = 23, 32, 21, True

In [46]:
#Printing several variables in one line using comma
name = "Gad"
age = 27
print(name, "is", age)

Gad is 27

In [47]:
#Printing several variables in one line using (+) symbol
name = "Gad"
age = 27
print(name+ " is " + str(age))

Gad is 27

In [51]:
#Using format key word to print values in one line using curly braces or braces
print("Hello! {} your age is {} and your height is {}".format(name, age, 1.78))

Hello! Gad your age is 27 and your height is 1.78

In [52]:
#Second way of print the results of variables using f
print(f"Hello! {name} your age is {age}")

Hello! Gad your age is 27

In [ ]:
# List
#Tuple
#Dictionnary

In [2]:
# You define a list by using [] square brackets
age = [30, 29, 34, 35, 36, 27, 25, 29,28, 30, 30]

In [3]:
#Slicing a list with index, first elements of the list age
age[:5]

[30, 29, 34, 35, 36]

In [4]:
#Last elements starting from 3rd
age[2:]

[34, 35, 36, 27, 25, 29, 28, 30, 30]

In [5]:
#Slice the age and get only 35, 36, 27, 25, 29
age[3:8]

[35, 36, 27, 25, 29]

In [61]:
#age[start:end:step]
#30, 35, 25, 30
age[:10:3]

[30, 35, 25, 30]

In [62]:
#Max to get the highest age value within the ag list
max(age)

36

In [63]:
#The smallest value with the age list
min(age)

25

In [68]:
#Sorting the values of age list
sorted_age = sorted(age, reverse = True)

In [69]:
print(sorted_age)

[36, 35, 34, 30, 30, 30, 29, 29, 28, 27, 25]

In [72]:
#A list contains a string data types
students = ["Eric", "Egid", "Augu", "Yvette", "Yvone", "Emmanuel", "Abel"]

In [73]:
print(type(students))

<class 'list'>

In [74]:
print(students[3])

Yvette

In [75]:
print(students[-3])

Yvone

In [77]:
#Change values of a list using the index or position of values
students[2] = "Augustin"

In [78]:
print(students) #lecture1.py

['Eric', 'Egid', 'Augustin', 'Yvette', 'Yvone', 'Emmanuel', 'Abel']

In [80]:
#Calculating tha total of the age list
sum(age)

333

## Python Collections (Arrays)
There are four collection data types in the Python programming language:

1. List is a collection which is ordered and changeable. Allows duplicate members. createed by []
2. Tuple is a collection which is ordered and unchangeable. Allows duplicate members. created by  ()
3. Dictionary is a collection which is ordered** and changeable. No duplicate members. created by {}
4. Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members. created by {}

## Possible options that we can perform on a list

In [52]:
# You define a list by using [] square brackets
age = [30, 29, 34, 35, 36, 27, 25, 29,28, 30, 30]
len(age)

11

In [55]:
# We can add elements to existing list using append, it updates variables inplace
age.append(26)

In [57]:
print(age)

[30, 29, 34, 35, 36, 27, 25, 29, 28, 30, 30, 31, 26]

In [58]:
# We can remove certain elements by referring to its index using pop
age.pop(5)

27

In [59]:
age

[30, 29, 34, 35, 36, 25, 29, 28, 30, 30, 31, 26]

In [60]:
# We can count how many times a certain element appears in the list using count
age.count(30)

3

In [61]:
#We can reverse the list
age.reverse()

In [62]:
print(age)

[26, 31, 30, 30, 28, 29, 25, 36, 35, 34, 29, 30]

In [64]:
#We can sort either ascending or descending order
age.sort(reverse= True)
print(age)

[36, 35, 34, 31, 30, 30, 30, 29, 29, 28, 26, 25]

In [65]:
#Adding more values within existing list, by spacifying index and values
age.insert(3, 35)

In [66]:
print(age)

[36, 35, 34, 35, 31, 30, 30, 30, 29, 29, 28, 26, 25]

In [68]:
#Deleting values by their values using remove
age.remove(30)
print(age)

[36, 35, 34, 35, 30, 30, 29, 29, 28, 26, 25]

In [ ]:
#This removes all items from my list
age.clear()

## String variables transformation

In [71]:
text = ' Welcome to pYthoN TOdAY  '

In [73]:
#This will convert all string/text/charactors in capital letters
text_cap = text.upper()
print(text_cap)

 WELCOME TO PYTHON TODAY

In [74]:
#Converting in small letters 
text_small = text.lower()
print(text_small)

 welcome to python today

In [75]:
len(text)

26

In [76]:
len('Welcome to pYthoN TOdAY')

23

In [77]:
#Removing the leading and lagging spaces
text_clean = text.strip()
print(len(text_clean))

23

In [79]:
#Converting the first char into capital and the rest to small
text_title = text.title()
print(text_title)

 Welcome To Python Today

In [82]:
#Counting number of times a char appear in a string
text_small.count('o')

4

## Creating a Tuple

In [86]:
#Defining a tuple with parantheses
names = ('Emma', 'Eric', 'joseph', 'Consolee', 'Yvette', 34, True)
print(type(names))

<class 'tuple'>

In [87]:
print(names)

('Emma', 'Eric', 'joseph', 'Consolee', 'Yvette', 34, True)

In [89]:
print(names[-5:-3])

('joseph', 'Consolee')

In [91]:
#Counting the number of times Emma appears in the tuple
names.count('Emma')

1

In [95]:
#Index or position a certain values belongs to
names.index('Emma')

0

In [96]:
# Adding a new value to tuple, convert to a list then do append then convert it back to a tuple
names_list = list(names) # Converting the available tuple into a list
names_list.append('Aimable') #Adding new name to a list
names = tuple(names_list) #converting back to a tuple format
print(names)

('Emma', 'Eric', 'joseph', 'Consolee', 'Yvette', 34, True, 'Aimable')

In [97]:
other_names = ('Nzira', 'Nicole')

In [107]:
#Concatinanting the tuples using +
all_names = names + other_names

In [108]:
print(all_names)

('Emma', 'Eric', 'joseph', 'Consolee', 'Yvette', 34, True, 'Aimable', 'Nzira', 'Nicole')

## Creating a Set in Python
Sets are used to store multiple items in a single variable
A set is unchangeable, unindexed, and unordered

In [132]:
# We create set by using {} curly braces
pet_animals = {"dog", "cat", "rabbit", "parrot", "cat", "hamster", "python", "cat"}
jungle_animals = {"tiger", "elephant", "monkey", "leopard", "python", "parrot"}
aquatic_animals = {"shark", "dolphin", "octopus", "seal", "jellyfish", "elephant"}

In [118]:
#Adding more elements to existing sets
pet_animals.add("tortoise")
print(pet_animals)

{'dog', 'hamster', 'python', 'rabbit', 'tortoise', 'cat', 'parrot'}

In [116]:
#This gives an error as sets do not have index
pet_animals[3]

TypeError: 'set' object is not subscriptable

In [119]:
#Checking the number of elements within sets
print(len(pet_animals))

7

In [124]:
# Removing elements from sets, remove command will give an error when element is not available
jungle_animals.remove("monkey")
print(jungle_animals)

{'elephant', 'python', 'leopard', 'tiger', 'parrot'}

In [126]:
# Delete randoom element using pop
jungle_animals.pop()
print(jungle_animals)

{'python', 'leopard', 'monkey', 'tiger', 'parrot'}

In [129]:
#Removing element and not get error if the not exists in the set
jungle_animals.discard("eleph")
print(jungle_animals)

{'elephant', 'python', 'leopard', 'monkey', 'tiger', 'parrot'}

In [130]:
#Completely all the elements of the set
jungle_animals.clear()
print(jungle_animals)

set()

In [133]:
#Finding smilar/common elements within different sets using intersection
print(pet_animals.intersection(jungle_animals))

{'python', 'parrot'}

In [134]:
# We can also use ampersand symbol to get the intersection
print(pet_animals & jungle_animals)

{'python', 'parrot'}

In [135]:
#Getting the union between several sets
print(pet_animals.union(jungle_animals))

{'dog', 'hamster', 'python', 'rabbit', 'leopard', 'monkey', 'cat', 'elephant', 'tiger', 'parrot'}

In [ ]:
#Getting union by using a symbol
print(pet_animals | jungle_animals)

In [138]:
#This issubset helps to know if a set belong to another
test = {"dog", "cat", "rabbit"}
print(test.issubset(pet_animals))

True

In [141]:
#Difference help to get the elements that do not appear in both sets
print(jungle_animals.issubset(aquatic_animals))
print(aquatic_animals.difference(jungle_animals))

False
{'octopus', 'jellyfish', 'shark', 'seal', 'dolphin'}

In [142]:
# Difference by using symbol (-)
print(aquatic_animals - jungle_animals)

{'octopus', 'jellyfish', 'shark', 'seal', 'dolphin'}

## Dictionary
Dictionaries are used to store data into keys and value, like JSON data format or NoSQL(MongoDB) data structure using curly braces

In [170]:
#Defining a dictionary using {} and key and values
"""
Dictionary doesn't have indexes
Dictionary do not allow duplicates
Dictionary is changeable and ordered since python version 3.7
"""
students = {
    "name":["Egide", "Eric", "Yvonne"],
    "age": [30],
    "gender": "male",
    "active": True
}
print(type(students))

<class 'dict'>

In [171]:
# Getting the values by using corresponding key
print(students.get("name"))

['Egide', 'Eric', 'Yvonne']

In [172]:
#Second options
students["age"]

[30]

In [173]:
#How to get all the keys
students.keys()

dict_keys(['name', 'age', 'gender', 'active'])

In [174]:
#Getting all the values from dict
students.values()

dict_values([['Egide', 'Eric', 'Yvonne'], [30], 'male', True])

In [175]:
#To add more keys or values on existing dictionary
students["grade"] = ["A" ,"B"]
print(students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30], 'gender': 'male', 'active': True, 'grade': ['A', 'B']}

In [176]:
#Updating the dict using update command
students.update({"weight" : 69})
print(students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30], 'gender': 'male', 'active': True, 'grade': ['A', 'B'], 'weight': 69}

In [177]:
#Using pop command to remove existing key from dict
students.pop("active")
print(students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30], 'gender': 'male', 'grade': ['A', 'B'], 'weight': 69}

In [178]:
#Deleting the active key and its corresponding values using del command
del students["active"]
print(students)

KeyError: 'active'

In [168]:
# Adding more values in the dict
students["grade"] = ["A" ,"B", "C", "D"]
print(students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': 30, 'gender': 'male', 'grade': ['A', 'B', 'C', 'D'], 'weight': 69}

In [179]:
# Appending more value to list values
students["grade"].append("E")
print(students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30], 'gender': 'male', 'grade': ['A', 'B', 'E'], 'weight': 69}

In [181]:
# Adding more values on the list
students["age"].extend([33, 26])

In [182]:
print(students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30, 33, 26], 'gender': 'male', 'grade': ['A', 'B', 'E'], 'weight': 69}

## Copy a Dictionary
We have two commands copy() and dict() for creating a copy of a dictionary

In [184]:
# Built-in dictionary method
students_new = students.copy()
print(students_new, students)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30, 33, 26], 'gender': 'male', 'grade': ['A', 'B', 'E'], 'weight': 69} {'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30, 33, 26], 'gender': 'male', 'grade': ['A', 'B', 'E'], 'weight': 69}

In [185]:
#Copying using DICT()
students_new_1 = dict(students_new)
print(students_new_1, students_new)

{'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30, 33, 26], 'gender': 'male', 'grade': ['A', 'B', 'E'], 'weight': 69} {'name': ['Egide', 'Eric', 'Yvonne'], 'age': [30, 33, 26], 'gender': 'male', 'grade': ['A', 'B', 'E'], 'weight': 69}

## Nested Dictionaries

In [187]:
#Creating a nested dict or subdict
school = {
    "class1" : {
        "email": "asedr@gmail.com",
        "name" : "Claude",
        "age": [23,34,28, 29]
    },

    "class2" : {
        "email": "asedr@ail.com",
        "name" : "Eric",
        "age": [23,33,28, 27]
    },
    "class3" : {
        "email": "asertdr@ail.com",
        "name" : "Eric",
        "age": [24,30,22, 23]
    },
    "class4" : students
}

In [190]:
#Slicing sub dictionary using keys and values
print(school["class4"]["grade"][1])

B

In [ ]:
#Slicing the dictionary
print(school["class3"]["age"][2])

In [ ]:
print(school["class4"]["age"])

## For and While Loops
for used to iterate over a sequence of list, tuple, number

In [194]:
#Defining age list using range
age = list(range(24, 55, 3))
print(age)

[24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54]

In [198]:
# Print the for loop with operations
for x in age:
    print(x-3)

21
24
27
30
33
36
39
42
45
48
51

In [199]:
# Storing the new computed vulues into a new list
age_new = []
for x in age:
    y = x-3
    age_new.append(y)
print(age_new)

[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51]

In [201]:
#Creating a simple for loop with range
for j in range(4,10,3):
    print(j-1)

3
6

## For Loop with Shorthand operation

In [7]:
#Double the number from 1 to 10
list1 = list(range(1, 11))
for t in list1:
    doubl = t*2
    print(doubl)

2
4
6
8
10
12
14
16
18
20

In [13]:
# Computing the factorial using for loop
n = 4
fact = 1
for g in range(1, n+1):
    fact = fact * g
print(fact)

24

In [14]:
# Computing the factorial using for loop with shorthand operation *=
n = 4
fact = 1
for g in range(1, n+1):
    fact *= g
print(fact)

24

In [19]:
# Calculating the total of the list elements using shorthand operation
total = 0
for e in range(1, 11):
    total += e
print("My sum is :", total)

My sum is : 55

## While Loop
It repat a block and checks for the condition, once the condition is true it gives the results otherwise stops

In [21]:

n = 2
while n <= 10:
    print("This number is less than 10 and is ", n)
    n += 1

This number is less than 10 and is  2
This number is less than 10 and is  3
This number is less than 10 and is  4
This number is less than 10 and is  5
This number is less than 10 and is  6
This number is less than 10 and is  7
This number is less than 10 and is  8
This number is less than 10 and is  9
This number is less than 10 and is  10

In [27]:
# Generate random number btwn 1 to 10 for guessing game
import random
secret = random.randint(1, 5)
guess = 0
while guess != secret:
    guess = int(input("Guess again and keep trying number (1-5)"))
print("You guessed it")

Guess again and keep trying number (1-5) 2
Guess again and keep trying number (1-5) 4
Guess again and keep trying number (1-5) 1
Guess again and keep trying number (1-5) 5

You guessed it

In [28]:
# Password guess program
password  = ""
while password != "python":
    password = input("Enter your password:")
print("Access granted")

Enter your password: names1
Enter your password: 234
Enter your password: 65uy
Enter your password: efrty
Enter your password: python

Access granted

In [ ]:
00001
33459
11789
78920
99999

In [34]:
# Password guess program with limiting the number of attempts
password  = ""
attempts = 0
while password != "python" and attempts <3:
    password = input("Enter your password:")
    attempts += 1
    print("You remain with {} Attempts More".format(3-attempts))
if password == "python":
    print("Access Granted")
else:
    print("You tried many times")

Enter your password: python

You remain with 2 Attempts More
Access Granted

In [37]:
# Password guess program with limiting the number of attempts and when password is not correct
password  = ""
attempts = 0
while password != "python" and attempts <3:
    password = input("Enter your password:")
    attempts += 1
    if password != "python":
        print("You remain with {} Attempts More".format(3-attempts))
if password == "python":
    print("Access Granted")
else:
    print("You tried many times")

Enter your password: dffshfb

You remain with 2 Attempts More

Enter your password: pyhton

You remain with 1 Attempts More

Enter your password: python

Access Granted

In [43]:
# Computation of Factorial using while loop
n = 5
factor = 1
while n > 0:
    factor *= n
    n -= 1
print(f"Factorial: {factor}")

Factorial: 120

In [46]:
# Printing Even numbers using While
even = 2
while even <30:
    even +=2
    print(even)

4
6
8
10
12
14
16
18
20
22
24
26
28
30

In [49]:
# Multiplication table
num  = 10
j = 1
while j <= 10:
    print(f"{num} x {j} = {num *j}")
    j +=1

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100

## Comparison operators
==,
!=, <>,
$>,$
$>,$
$<,$
$>=,$
$<=,$

In [ ]:
 age > 40 and age <50

## Conditions and IF Stements
Python supports the usual logical conditions from mathematics:
1.  Equals: $a == b$
2.  Not equal: $a != b$
3.  Less than: $a < b$
4.   Less than or equal to : $a <= b$
5.   Greater than: $a>b$
6.   Greater than or equal to : $a >=b$

In [52]:
#Comparing the numbers
x = 5
y = 2
if y > x:
    print("Y is greater than X") # 4 spaces for identation

In [58]:
#The use of elif keyword
a = 22
b = 79
if b < a:
    print("B is smaller than A")
elif b > a:
    print("B is greater than A")
else: #All the top conditions are false
    print("B is equal to A")

B is greater than A

In [67]:
#Checking if a number is even or odd
num = 38
if num % 2 == 0:
    print("This number is even")
else:
    print("This number is odd")

This number is even

In [71]:
# Print the numbers from 1 to 100 that are dividable by 7
for t in range(1, 20):
    if t % 7 == 0:
        print(t)

7
14

In [74]:
# oNE LINE IF ELSE STATEMENT
t = 30
u = 36
print("U is greater") if u > t else print("T is greater or egual to U ")

U is greater

In [82]:
# Combining the conditions test with AND OR
r = 40
g = 70
k = 90
e = 33
if e % 3 == 0 and k > g:
    print("1. Both conditions are true")
else:
    print("2. Both conditions are not true")

1. Both conditions are true

In [84]:
#The application of OR keyword in IF statement
r = 40
g = 70
k = 90
e = 33
if e % 3 == 1 or k < g:
    print("1. Both conditions are true")
else:
    print("2. Both conditions are not true")

2. Both conditions are not true

In [86]:
# Combining the logical tests with AND
if 1 == True and 0 == False:
    print("Both conditions are true")
else:
    print("Both conditions are not true")

Both conditions are true

In [93]:
# combining OR and AND in one logical test
r = 40
g = 70
k = 90
e = 33
if (e % 3 == 1 or k > g) and (r < g and g < e):
    print("1. Both conditions are true")
else:
    print("2. Both conditions are not true")

2. Both conditions are not true

In [96]:
# Using NOT keyword in if statments
r = 40
g = 70
k = 90
e = 33
if (e % 3 == 1 or k > g) and (r < g and not g < e):
    print("1. Both conditions are true")
else:
    print("2. Both conditions are not true")

1. Both conditions are true

In [101]:
# COMBINING OR AND NOT in one logical test
r = 40
g = 70
k = 90
e = 33
if (not (e % 3 == 1 or k > g)) and (r < g and not g < e):
    print("1. Both conditions are true")
else:
    print("2. Both conditions are not true")

2. Both conditions are not true

## Exercises

In [102]:
x = 5
y = 8
if x > y:
  print('Hello')
else:
  print('Welcome')

Welcome

In [ ]:
print("Number is positive")
print("Number is negative")
print("Number is zero")

In [108]:
# Input marks from 1 to 100 and print the grade
# A (90+), B (75 - 89), C (50-74), F (<50)
mark = int(input("Enter your marks"))

if mark >= 90:
    print("A")
elif mark >= 75:
    print("B")
elif mark >= 50:
    print("C")
else:
    print("F")

Enter your marks 55

C

In [109]:
# IF statements with keywords like break, continue, pass
#Break used to stop the entire loop at specified condition/position
for f in range(1, 6):
    if f == 4:
        break
    print(f)

1
2
3

In [110]:
# Breaking the look at a number that is dividable by 3
for f in range(2, 9, 2):
    if f % 3 == 0:
        break
    print(f)

2

In [114]:
#Skips the current iteration and moves to the next iteration
for f in range(2, 20, 2):
    if f % 3 == 0:
        continue
    print(f)

2
4
8
10
14
16

In [115]:
# Examples to be solved by you
for t in range(11):
    if t % 5 == 1:
        continue
    if t == 8:
        break
    print(t)

[2, 5, 8]

## Leap year check calculation

Ask for a year. 
1. If divisible by 400 → "Leap year".
2. Else if divisible by 4 but not by 100 → "Leap year".
3. Otherwise → "Not a leap year".

In [127]:
year = int(input("Enter the year:"))
if year % 400 == 0:
    print("Leap year")
elif year % 4 ==0 and year % 100 != 0:
    print("Leap Year")
else:
    print("Not Leap Year")

Enter the year: 2005

Not Leap Year


## BMI Calculator use IF, ELIF and ELSE

Input weight (kg) and height (m).
Calculate BMI = weight / height².
Classify: 
1. <18.5 → "Underweight"
2. 18.5–24.9 → "Normal"
3. 25–29.9 → "Overweight"
4. ≥30 → "Obese"

In [130]:
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in m: "))

bmi = weight / (height ** 2)

if bmi < 18.5:
    print("Underweight")
elif bmi <= 24.9:
    print("Normal")
elif bmi <= 29.9:
    print("Overweight")
else:
    print("Obese")

Enter your weight in kg:  60
Enter your height in m:  1.62

Normal

In [131]:
# In the number between 1 to 100, find the numbers 
# that are divisible by 3 and 7
for i in range(1, 101):
    if i % 3 == 0 and i % 7 == 0:
        print(i)

21
42
63
84

In [132]:
# In the number between 1 to 100, find the numbers 
# that are divisible by 3 and 7 and even numbers only
for i in range(1, 101):
    if i % 3 == 0 and i % 7 == 0 and i % 2 == 0:
        print(i)

42
84

## Introduction on Functions 
keyword used to define a function _def_

In [6]:
# Defining first function without parameters
def first_funct():
    print("Welcome to Python")

In [7]:
#Calling the function
first_funct()

Welcome to Python

### Function with Arguments
Passing information inside the function

In [11]:
# This function need argument of last_name
def welcome(last_name):
    print("Welcome to Python " + last_name + "!")

In [16]:

#Calling the function with last_name as input
welcome("Ansah")
welcome("Eric")
welcome("Aimable")
welcome("Bismark")

Welcome to Python Ansah!
Welcome to Python Eric!
Welcome to Python Aimable!
Welcome to Python Bismark!

In [17]:
# Function with many arguments for addition
def addition(r, n ,j):
    print(r + n + j)

In [19]:
# Getting the addition results
addition(4, 2, 1)

7

In [21]:
# You will get error when the passed inputs are not the same as defined parameters
addition(3,2,3,1)

TypeError: addition() takes 3 positional arguments but 4 were given

In [22]:
#Function  with default parameter values
def my_function(name = "Blossom"):
    print("Welcome to " + name)

In [25]:
my_function("Kaggle")
my_function()
my_function("DataCamp")

Welcome to Kaggle
Welcome to Blossom
Welcome to DataCamp

In [35]:
# Taking the list as inputs then return the same list as capital letters
names = ["Yvonne", "Pamela", "Augustin"] #It can be a list or column of a table
def capital(students_names):
    names_cap = []
    for i in students_names:
        names_cap.append(i.upper())
    print(names_cap)

In [36]:
capital(fruits)

['BANANA', 'BANANA', 'APPLE', 'MANGO']

In [31]:
fruits = ["Banana", "banana", "appLE", "MAngO"]

In [37]:
# Taking the list as inputs then return the same list as capital letters
names = ["Yvonne", "Pamela", "Augustin"] #It can be a list or column of a table
def small_letters(students_names):
    names_cap = []
    for i in students_names:
        names_cap.append(i.lower())
    print(names_cap)

In [38]:
small_letters(fruits)

['banana', 'banana', 'apple', 'mango']

### The use of return as function output

In [50]:
def mltp(w,g):
    return w * g
    print("Welcome to Python")

In [51]:
mltp(6,5) * 2

60

In [45]:
def mltp_print(w,g):
    print("Welcome to Python")
    return w * g

In [52]:
mltp_print(5,2) * 3

Welcome to Python

30

In [53]:

def area_rectangle(h, w):
    return h * w / 2

In [55]:
area_rectangle(20, 30)

300.0

In [57]:
import numpy as np

In [58]:
np.pi

3.141592653589793

In [61]:
# Using return to get area of cicle and using numpy libraries
import numpy as np
def area_cicle(r):
    return r**2 * np.pi

In [63]:
area_cicle(2)

12.566370614359172

In [ ]:
bmi(1.67, 67)

In [65]:
def bmi(h,w):
    return w / h**2

In [68]:
bmi(1.7, 80)

27.68166089965398

### Python Lambda Function
Syntax:  
lambda arguments: expression

In [70]:
#Addition using lambda
add = lambda e,w,q : e + q + w
add(4,1,0)

5

In [71]:
#Error when arguments are not equal
add(4,2,3,1,9)

TypeError: <lambda>() takes 3 positional arguments but 5 were given

In [72]:
#Square the elements of the list using map
num = [3,5,7,1,9]
square = list(map(lambda x: x**2, num))
print(square)

[9, 25, 49, 1, 81]

In [74]:
#Absolute values (changing negative to positive) the elements of the list using map
num = [3,-5,7,-100,-9]
absolu = list(map(lambda x: abs(x), num))
print(absolu)

[3, 5, 7, 100, 9]

## Exception Handling
This is the way of monitoring the errors in python using keywords like *try, except, else, and finally*

*Try* block lets you test the codes for error

*Except* lets you handle the error

In [51]:
# Checking if the variable is defined before
try:
    print(p)
except:
    print("An error has occured")

An error has occured

In [19]:
#Division by Zero error handling
def divide(d, k):
    result = d / k
    return result

In [66]:
# Handling the zero division error
def divide(d, k):
    try:
        result = d / k
        print(result)
    except ZeroDivisionError:
        print("Error: Cannot divide by zero")
    except TypeError:
        print("Error: Both are not numbers")

In [72]:
# Data type converting error handling ValueError
try:
    print(int("20 years"))
except ValueError:
    print("You can't convert text to integer")

You can't convert text to integer

In [84]:
#### Withdram program
balance = 150
try:
    amount = int(input("Enter amount to withdram:"))
    if amount >= balance:
        print("Error Insufficient funds")
    else:
        balance -= amount
        print("Withdram seccussful, New balance:", balance) 
except ValueError:
     print("Error: Please the number")
finally:
    print("Program Ends Here!!")

Enter amount to withdram: hg

Error: Please the number
Program Ends Here!!

## Libraries or Packages in Python
Introduction to NUMPY: scientific computing , algebra

In [86]:
# Importing library with abbreviation of np
import numpy as np

In [89]:
#Matrix of  4X4 zeros
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
#Matrix of  1X1 ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
# Defining a list/array with start, end and step
np.linspace(20, 40, 21)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35., 36., 37., 38., 39., 40.])

In [98]:
#Identical matrix of 4X4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## More examples of Numpy 
numpy array stores one data type unlike the normal list
Array takes small space on the disk

In [101]:
# Normal list
ages = [23, 45, 21.5, "27years", 30]

In [102]:
## Shape used size (rows and columns) of array or table
data = np.arange(2, 25, 2)
print(data)

[ 2  4  6  8 10 12 14 16 18 20 22 24]

In [104]:
# Type help the variable data type
type(data)

numpy.ndarray

In [105]:
# Size
data.shape

(12,)

In [107]:
# Checking the size of a matrix
matrix = np.ones((20, 5))
matrix.shape

(20, 5)

In [108]:
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
# Converting booleans into integer, means int > boolean
list1 = [True, 3, 5, False]
list1_array = np.array(list1)
print(list1_array)

[1 3 5 0]

In [112]:
# Converting into float from Boolean and int
list1 = [True, 2.4, 3, 5, 1.1]
list1_array = np.array(list1)
print(list1_array)

[1.  2.4 3.  5.  1.1]

In [119]:
# Converting every data points into strings, str > float > int > boolean 
list1 = [True, 2.4, 3, 5, 1.1, False,  20, "5years"]
list1_array = np.array(list1)
print(list1_array)

['True' '2.4' '3' '5' '1.1' 'False' '20' '5years']

In [152]:
## Mathematical Operations using numpy arrays
weights1 = np.array([65, 67, 63, 54, 90, 43, 23, 25])
weights2 = np.array([24, 26, 30, 12, 14, 18, 29, 11])
#Addition of weights
total_weights = weights1 + weights2

#Multiplication
print(weights1 * 3)

#Division
print(weights2 / 2)

[195 201 189 162 270 129  69  75]
[12.  13.  15.   6.   7.   9.  14.5  5.5]

In [156]:
#Statistical  Operations or functions within numpy
print("Sum of weights1:" , np.sum(weights1))
print("Average of weights1:" , np.mean(weights1))
print("Media of weights1:" , np.median(weights1))
print("Minimun value is:",np.min(weights1))
print("Maximun value is:",np.max(weights1))

Sum of weights1: 430
Average of weights1: 53.75
Media of weights1: 58.5
Minimun value is: 23
Maximun value is: 90

In [164]:
# Indexing anf slicing the numpy array
print(weights1[0]) #The first element
print(weights1[-1]) # The last element
print(weights1)

65
25
[65 67 63 54 90 43 23 25]

In [166]:
print("1.", weights1[3:6])
print("2." ,weights1[:2])
print("3.", weights1[5:])
print("4.", weights1 [-2:]) #All except last 2 elements
print("5.", weights1[:-3])

1. [54 90 43]
2. [65 67]
3. [43 23 25]
4. [23 25]
5. [65 67 63 54 90]

In [189]:
#Initializing random number array or matrix using numpy
#Array of 5 elements below 10
print(np.random.randint(10, size = 5))

[7 9 8 7 7]

In [192]:
#Matric of 3X4 using randint
print(np.random.randint(20, size = (3,4)))

[[19  7 18  4]
 [15 13 10 13]
 [ 5 10 13  7]]

In [193]:
#Random Array Floats between 0 and 1
np.random.rand(4)

[0.55350147 0.38021281 0.96856782 0.3984923 ]

In [197]:
#Random Matrix Floats between 0 and 1
matrix2 = np.random.rand(4, 3)
print(matrix2)

[[0.87321506 0.17382264 0.00832078]
 [0.44584201 0.77692233 0.72183748]
 [0.01237794 0.50387499 0.39153921]
 [0.4349348  0.49146553 0.80977509]]

In [199]:
# Reshaping the array or matrix
reshaped_matrix1 = matrix2.reshape(2,6)
print(reshaped_matrix1)

[[0.87321506 0.17382264 0.00832078 0.44584201 0.77692233 0.72183748]
 [0.01237794 0.50387499 0.39153921 0.4349348  0.49146553 0.80977509]]

In [200]:
# Reshaping the array or matrix
reshaped_matrix2 = matrix2.reshape(6,2)
print(reshaped_matrix2)

[[0.87321506 0.17382264]
 [0.00832078 0.44584201]
 [0.77692233 0.72183748]
 [0.01237794 0.50387499]
 [0.39153921 0.4349348 ]
 [0.49146553 0.80977509]]

In [210]:
# Reshaping the array or matrix
reshaped_matrix3 = matrix2.reshape(3, 7)
print(reshaped_matrix3)

ValueError: cannot reshape array of size 12 into shape (3,7)

In [216]:
## Matrix Transponse: switching rows to columns or switching columns to rows
mat1 = np.random.randint(10, size = (4,4))
print(mat1)

[[1 9 3 6]
 [0 9 2 0]
 [9 8 1 8]
 [8 1 2 4]]

In [217]:
#UsinG .T to perform matrix transpose
print(mat1.T)

[[1 0 9 8]
 [9 9 8 1]
 [3 2 1 2]
 [6 0 8 4]]

In [218]:
# Total of the diagonal elements
np.trace(mat1)

15

In [232]:
## Sum two matrices
mat1 = np.random.randint(20, size = (5,5))
mat2 = np.random.randint(20, size = (5,5))
print("mat1 \n", mat1)
print("mat2 \n" ,mat2)
print("total \n", mat1 + mat2)

mat1
 [[ 0  2  7 13  9]
 [14 13  4 15  0]
 [12  2  2  1  5]
 [ 7 10  8  7  4]
 [18  8 11 11 16]]
mat2
 [[ 1  7  6  2 13]
 [ 3 18 12 18  0]
 [16 12 17 13  8]
 [ 0 11 16  1  5]
 [ 5  8 19 19 10]]
total
 [[ 1  9 13 15 22]
 [17 31 16 33  0]
 [28 14 19 14 13]
 [ 7 21 24  8  9]
 [23 16 30 30 26]]

In [223]:
# Sum all the elements of the matrix
np.sum(mat1)

214

In [224]:
#Sum elements column or row wise
mat3 = np.random.randint(10, size = (3,2))
print(mat3)

[[6 5]
 [9 3]
 [3 6]]

In [226]:
#Suming columnwise elements of a matrix using axis = 0
np.sum(mat3, axis= 0)

array([18, 14])

In [227]:
#Suming row-wise elements of a matrix using axis = 1
np.sum(mat3, axis= 1)

array([11, 12,  9])

In [236]:
doube_mat1 = np.random.randint(10, size = (2,1)) + mat1
doube_mat1

ValueError: operands could not be broadcast together with shapes (2,1) (5,5)

In [243]:
## Determinant of a matrix
mat4 = np.random.randint(10, size = (2,2))
print("Matrice 4 \n",mat4)
print("Determinant \n",np.round(np.linalg.det(mat4)))

Matrice 4
 [[6 3]
 [8 3]]
Determinant
 -6.0

In [245]:
#In case mat4 is confusion mattrix, accuracy can be computed as follow:
np.trace(mat4)/np.sum(mat4)

0.45

In [246]:
## Filtering the arrays
age = np.random.randint(20, 80, 30)
print(age)

[25 66 78 71 66 36 38 46 26 34 76 38 46 25 57 20 24 54 52 39 47 31 66 39
 76 37 30 68 70 68]

In [252]:
##Getting the age that are greater than 40
age[age > 40]

array([66, 78, 71, 66, 46, 76, 46, 57, 54, 52, 47, 66, 76, 68, 70, 68])

In [258]:
##Getting the age that are greater than 40 and less than 70 years old
age[(age > 40) & (age < 70)]

array([66, 66, 46, 46, 57, 54, 52, 47, 66, 68, 68])

In [260]:
##Getting the age that are greater than 70 or less than 30 years old
age[(age < 30) | (age > 70)]

array([25, 78, 71, 26, 76, 25, 20, 24, 76])

In [285]:
# Filter a text/string array
region = np.array(["East", "South", "West", "North", "East", "South", "West", "North","East", "South", "West", "North"
                  "East", "South", "West", "North","East", "South", "West", "North"])

In [278]:
#Filter list array with OR symbol
region[(region == "East") | (region == "West")]

array(['East', 'West', 'East', 'West', 'East', 'West', 'West', 'East',
       'West'], dtype='<U9')

In [279]:
#Excluding conditions
region[(region == "East") & (region == "West")]

array([], dtype='<U9')

In [283]:
## Application of dot product and SUMPRODUCT in EXCEL
qty = np.array([1,2,3,2])
price =np.array([100, 50, 200, 20])
print("Total Sales is:", np.dot(qty , price))

Total Sales is: 840

## Pandas Library for data manipulation
Basic of data cleaning and manipulation from dictionary

In [284]:
#Importing from PANDAS
import pandas as pd

In [291]:
#Dictionary of region and age
data = {
    "region" : list(region),
    "age" : np.random.randint(20, 50, size = 19)
}

In [294]:
#Convert a data dictionary into a pandas dataframe
df = pd.DataFrame(data)
## Showing the top first rows using head()
print(df.head(10))
##Show top last rows using tail()

  region  age
0   East   41
1  South   38
2   West   28
3  North   34
4   East   26
5  South   26
6   West   34
7  North   29
8   East   24
9  South   36

In [295]:

##Show top last rows using tail()
print(df.tail(10))

       region  age
9       South   36
10       West   41
11  NorthEast   28
12      South   39
13       West   31
14      North   49
15       East   44
16      South   40
17       West   24
18      North   32

## More Examples on Pandas Library

In [3]:
#Importing the pandas library
import pandas as pd

In [8]:
import pandas as pd
#Reading csv file using pandas
employees = pd.read_csv("employees_data.csv")

#showing the first 10 rows
print(employees.head(10))
print("_"* 50)
#showing the last 10 rows
print(employees.tail(10))

   ID     Name   Age  Department  Salary     City
0   1    Helen  47.0   Marketing   71631  Kampala
1   2  Charlie  51.0          IT   86050  Kampala
2   3   Fatima  47.0  Operations   89827  Kampala
3   4   Fatima  36.0          IT   72871   Arusha
4   5      Ian  52.0     Finance   83569  Kampala
5   6    Alice  30.0   Marketing   70833  Nairobi
6   7   George  38.0          HR   58860   Lusaka
7   8     Jane  31.0  Operations   60921   Arusha
8   9   George   NaN     Finance   89566  Nairobi
9  10  Charlie  52.0     Finance   62632   Arusha
__________________________________________________
      ID     Name   Age  Department  Salary     City
113  114      NaN  55.0          HR   56460  Kampala
114  115   George  43.0          HR   88383   Kigali
115  116     Eric  51.0     Finance   44349      NaN
116  117     Eric  38.0     Finance   74402  Kampala
117  118    Diana  54.0     Finance   44606   Arusha
118  119    Helen  25.0  Operations   67811   Kigali
119  120      Ian  32.0   Marketing   83752   Lusaka
120  109  Charlie  35.0          IT   70411  Nairobi
121  110     Eric  26.0          HR   68833  Nairobi
122  111    Helen  22.0          IT   68356  Nairobi

In [2]:
#Checking the data type of employees, it is DataFrame
print(type(employees))

<class 'pandas.core.frame.DataFrame'>

In [3]:
# Showing the number of rows/records (123) and columns (6)
print(employees.shape)

(123, 6)

In [4]:
#INFO helps to get data types of every column and non-null values
print(employees.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          123 non-null    int64
 1   Name        121 non-null    object
 2   Age         121 non-null    float64
 3   Department  122 non-null    object
 4   Salary      123 non-null    int64
 5   City        120 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 5.9+ KB
None

In [5]:
#Quick summary statistics on every numerical columns
print(employees.describe())

               ID         Age        Salary
count  123.000000  121.000000    123.000000
mean    61.707317   38.743802  67338.333333
std     35.200068    9.590385  14088.386385
min      1.000000   22.000000  40451.000000
25%     31.500000   31.000000  56789.000000
50%     62.000000   38.000000  68833.000000
75%     92.500000   47.000000  78808.000000
max    120.000000   55.000000  89827.000000

In [6]:
#Selecting specific data points by column names
print(employees[["Age", "Salary"]])

      Age  Salary
0    47.0   71631
1    51.0   86050
2    47.0   89827
3    36.0   72871
4    52.0   83569
..    ...     ...
118  25.0   67811
119  32.0   83752
120  35.0   70411
121  26.0   68833
122  22.0   68356

[123 rows x 2 columns]

In [7]:
#Using copy to clear exactly the same data with diff variable names
employees_clear = employees.copy()
print(employees_clear.shape)

(123, 6)

In [8]:
#Filtering the rows with Age above 45
employees_clear[employees_clear['Age'] > 45]

      ID     Name   Age  Department  Salary     City
0      1    Helen  47.0   Marketing   71631  Kampala
1      2  Charlie  51.0          IT   86050  Kampala
2      3   Fatima  47.0  Operations   89827  Kampala
4      5      Ian  52.0     Finance   83569  Kampala
9     10  Charlie  52.0     Finance   62632   Arusha
19    20    Diana  50.0  Operations   49651  Kampala
27    28      Ian  50.0          HR   87007   Kigali
40    41    Alice  46.0          HR   87808  Nairobi
41    42    Diana  52.0          HR   86572   Kigali
45    46  Charlie  48.0          IT   73500  Kampala
46    47     Jane  50.0     Finance   77914   Kigali
53    54   Fatima  52.0   Marketing   42251  Kampala
57    58     Eric  51.0          HR   79491  Kampala
60    61     Jane  50.0   Marketing   85880   Lusaka
65    66   George  54.0  Operations   63471  Nairobi
66    67    Alice  46.0   Marketing   76852  Kampala
67    68     Eric  55.0     Finance   54622  Nairobi
68    69      Bob  51.0   Marketing   48946   Lusaka
72    73      Bob  51.0   Marketing   86036   Kigali
73    74    Helen  46.0          IT   69781  Nairobi
74    75      Ian  50.0   Marketing   81351  Nairobi
81    82  Charlie  51.0          IT   57459  Nairobi
82    83  Charlie  53.0  Operations   57285   Arusha
83    84    Diana  49.0         NaN   85582  Kampala
85    86      Bob  48.0          HR   69744  Kampala
86    87   Fatima  47.0   Marketing   86433   Kigali
89    90   George  50.0   Marketing   78210   Arusha
95    96      Ian  46.0  Operations   65714   Arusha
97    98      NaN  48.0   Marketing   43828   Kigali
98    99   Fatima  47.0   Marketing   76104  Nairobi
99   100    Helen  54.0          IT   61349   Kigali
102  103   George  48.0  Operations   57497  Kampala
103  104      Ian  48.0          HR   68192  Kampala
107  108      Ian  50.0          HR   82014   Lusaka
112  113      Bob  55.0          IT   62140  Nairobi
113  114      NaN  55.0          HR   56460  Kampala
115  116     Eric  51.0     Finance   44349      NaN
117  118    Diana  54.0     Finance   44606   Arusha

In [9]:
#Filtering the rows with Age above 45 and also in Kampala
print(employees_clear[(employees_clear['Age'] > 45) & (employees_clear['City'] == 'Kampala')])

      ID     Name   Age  Department  Salary     City
0      1    Helen  47.0   Marketing   71631  Kampala
1      2  Charlie  51.0          IT   86050  Kampala
2      3   Fatima  47.0  Operations   89827  Kampala
4      5      Ian  52.0     Finance   83569  Kampala
19    20    Diana  50.0  Operations   49651  Kampala
45    46  Charlie  48.0          IT   73500  Kampala
53    54   Fatima  52.0   Marketing   42251  Kampala
57    58     Eric  51.0          HR   79491  Kampala
66    67    Alice  46.0   Marketing   76852  Kampala
83    84    Diana  49.0         NaN   85582  Kampala
85    86      Bob  48.0          HR   69744  Kampala
102  103   George  48.0  Operations   57497  Kampala
103  104      Ian  48.0          HR   68192  Kampala
113  114      NaN  55.0          HR   56460  Kampala

In [10]:
## Storing filterred output as new variables
kampala_empl_45 = employees_clear[(employees_clear['Age'] > 45) & (employees_clear['City'] == 'Kampala')]

In [11]:
#Saving the cleaned data to disk of folder
kampala_empl_45.to_csv("kampla employees greater than 45.csv")

In [12]:
#Creating a new column based on existing columns on dataframe
employees_clear["Final Salary"] = employees_clear["Salary"] + 5000
print(employees_clear.head())

   ID     Name   Age  Department  Salary     City  Final Salary
0   1    Helen  47.0   Marketing   71631  Kampala         76631
1   2  Charlie  51.0          IT   86050  Kampala         91050
2   3   Fatima  47.0  Operations   89827  Kampala         94827
3   4   Fatima  36.0          IT   72871   Arusha         77871
4   5      Ian  52.0     Finance   83569  Kampala         88569

In [13]:
#Adding a new column of ratio which Salary over Age
employees_clear["Ratio"]  = employees_clear["Salary"] / employees_clear["Age"]
print(employees_clear.head())

   ID     Name   Age  Department  Salary     City  Final Salary        Ratio
0   1    Helen  47.0   Marketing   71631  Kampala         76631  1524.063830
1   2  Charlie  51.0          IT   86050  Kampala         91050  1687.254902
2   3   Fatima  47.0  Operations   89827  Kampala         94827  1911.212766
3   4   Fatima  36.0          IT   72871   Arusha         77871  2024.194444
4   5      Ian  52.0     Finance   83569  Kampala         88569  1607.096154

In [14]:
# Slicing a dataframe using iloc and loc
 #iloc uses index or position
#loc uses the label or name

In [15]:
#Only for rows index number
print(employees_clear.iloc[5:10])

   ID     Name   Age  Department  Salary     City  Final Salary        Ratio
5   6    Alice  30.0   Marketing   70833  Nairobi         75833  2361.100000
6   7   George  38.0          HR   58860   Lusaka         63860  1548.947368
7   8     Jane  31.0  Operations   60921   Arusha         65921  1965.193548
8   9   George   NaN     Finance   89566  Nairobi         94566          NaN
9  10  Charlie  52.0     Finance   62632   Arusha         67632  1204.461538

In [19]:
#Slicing using index number and column index number
employees_clear.iloc[50:65, [1,4, 6, 2]]

      Name  Salary  Final Salary   Age
50     Ian   74939         79939  44.0
51    Eric   80829         85829  22.0
52   Alice   76425         81425  34.0
53  Fatima   42251         47251  52.0
54   Diana   44591         49591  22.0
55  George   87593         92593  32.0
56     Bob   72776         77776  45.0
57    Eric   79491         84491  51.0
58    Jane   41658         46658  31.0
59  Fatima   63941         68941  28.0
60    Jane   85880         90880  50.0
61   Helen   65130         70130  35.0
62   Alice   55181         60181  39.0
63   Diana   69561         74561  42.0
64  Fatima   54714         59714  40.0

## Sept 26th 2025 Introduction to Pandas
More examples of pandas for data manipulation

In [35]:
## Using label instead of indexes
#2,4 "Age", "Salary"
employees_clear.loc[9, 'Name']

'Charlie'

In [28]:
#Show column names within dataframe
employees_clear.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary', 'City', 'Final Salary',
       'Ratio'],
      dtype='object')

In [38]:
## Using labels instead of indexes
#2,4 "Age", "Salary"
employees_clear.loc[9, ['Name', 'Salary', 'City']]

Name      Charlie
Salary      62632
City       Arusha
Name: 9, dtype: object

In [39]:
## Using labels instead of indexes
#2,4 "Age", "Salary"
employees_clear.loc[5:9, ['Name', 'Salary', 'City']]

      Name  Salary     City
5    Alice   70833  Nairobi
6   George   58860   Lusaka
7     Jane   60921   Arusha
8   George   89566  Nairobi
9  Charlie   62632   Arusha

In [40]:
# Using labels instead of indexes
#2,4 "Age", "Salary"
employees_clear.loc[[2,5,8,15], ['Name', 'Salary', 'City']]

      Name  Salary     City
2   Fatima   89827  Kampala
5    Alice   70833  Nairobi
8   George   89566  Nairobi
15   Alice   64696   Arusha

In [42]:
## Update or change a values from df
employees_clear.iloc[2, 4] = 80000

In [44]:
# Filterring using loc keep Nairobi NAME, SALARY AND CITY
employees_clear.loc[employees_clear['City']  == 'Nairobi', ['Name', 'Salary', 'City']]

        Name  Salary     City
5      Alice   70833  Nairobi
8     George   89566  Nairobi
12   Charlie   88244  Nairobi
22    George   66517  Nairobi
23     Diana   50425  Nairobi
31     Diana   81395  Nairobi
40     Alice   87808  Nairobi
43       Ian   51768  Nairobi
44       Ian   64012  Nairobi
49    Fatima   61143  Nairobi
51      Eric   80829  Nairobi
52     Alice   76425  Nairobi
56       Bob   72776  Nairobi
65    George   63471  Nairobi
67      Eric   54622  Nairobi
71    Fatima   49365  Nairobi
73     Helen   69781  Nairobi
74       Ian   81351  Nairobi
81   Charlie   57459  Nairobi
84   Charlie   50457  Nairobi
94      Jane   74319  Nairobi
98    Fatima   76104  Nairobi
105      Bob   75886  Nairobi
108  Charlie   70411  Nairobi
109     Eric   68833  Nairobi
110    Helen   68356  Nairobi
111  Charlie   56138  Nairobi
112      Bob   62140  Nairobi
120  Charlie   70411  Nairobi
121     Eric   68833  Nairobi
122    Helen   68356  Nairobi

In [ ]:
# Filterring using iloc keep Nairobi NAME, SALARY AND CITY
employees_clear.loc[employees_clear['City']  == 'Nairobi', ['Name', 'Salary', 'City', 'Age']]

In [45]:
employees_clear.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary', 'City', 'Final Salary',
       'Ratio'],
      dtype='object')

## Handling missing values

In [51]:
# Identifying missing values using isna() or isnull()
employees_clear.isnull().sum()

ID              0
Name            2
Age             2
Department      1
Salary          0
City            3
Final Salary    0
Ratio           2
dtype: int64

In [52]:
## Droping or deleting rows with missing values
employee_no_missing = employees_clear.dropna()

In [57]:
#Checking the size of cleaned dataframe
print(employees_clear.shape)
print("-" * 10)
print(employee_no_missing.shape)

(123, 8)
----------
(115, 8)

In [58]:
## Dropping a column with missing value
employee_col_no_missing = employees_clear.dropna(axis= 1)

In [59]:
employee_col_no_missing.shape

(123, 3)

In [62]:
# Droping missing values with subset
employees_name_no_missing = employees_clear.dropna(subset= ['Name', 'Department'])

In [63]:
employees_name_no_missing.shape

(120, 8)

In [64]:
#Saving the cleaned dataframe as attachment or excel
employees_name_no_missing.to_excel("names no missing.xlsx")

,ID,Name,Age,Department,Salary,City,Final Salary,Ratio
0,1,Helen,47.0,Marketing,71631,Kampala,76631,1524.063830
1,2,Charlie,51.0,IT,86050,Kampala,91050,1687.254902
2,3,Fatima,47.0,Operations,80000,Kampala,94827,1911.212766
3,4,Fatima,36.0,IT,72871,Arusha,77871,2024.194444
4,5,Ian,52.0,Finance,83569,Kampala,88569,1607.096154
...,...,...,...,...,...,...,...,...
118,119,Helen,25.0,Operations,67811,Kigali,72811,2712.440000
119,120,Ian,32.0,Marketing,83752,Lusaka,88752,2617.250000
120,109,Charlie,35.0,IT,70411,Nairobi,75411,2011.742857
121,110,Eric,26.0,HR,68833,Nairobi,73833,2647.423077
122,111,Helen,22.0,IT,68356,Nairobi,73356,3107.090909

In [65]:
## Imputation or replacing missing values
#Replace with zero with missing age
employees_clear["Age"].fillna(0, inplace= True)
employees_clear.isna().sum()

ID              0
Name            2
Age             0
Department      1
Salary          0
City            3
Final Salary    0
Ratio           2
dtype: int64

In [14]:
## Imputation or replacing missing values
#Replace with average missing ratio when there are not Outliers
employees_clear["Ratio"].fillna(employees_clear["Ratio"].mean(), inplace= True)
employees_clear.isna().sum()

ID              0
Name            2
Age             2
Department      1
Salary          0
City            3
Final Salary    0
Ratio           0
dtype: int64

In [34]:
employees_clear.isnull().sum()

ID              0
Name            2
Age             0
Department      1
Salary          0
City            0
Final Salary    0
Ratio           0
dtype: int64

In [16]:
## Imputation or replacing missing values
#Replace with median missing ratio when there are Outliers
employees_clear["Age"].fillna(employees_clear["Age"].median(), inplace= True)

In [29]:
#Handling missing values using mode for categorical
employees_clear["City"].mode()[0]

'Nairobi'

In [20]:
#Number of times any city appears in the dataframe
employees_clear["City"].value_counts()

City
Nairobi    31
Kampala    30
Kigali     23
Arusha     20
Lusaka     16
Name: count, dtype: int64

In [30]:
#Replace missing city with mode
employees_clear["City"].fillna(employees_clear["City"].mode()[0], inplace= True)

In [32]:
#Number of times any city appears in the dataframe
employees_clear["City"].value_counts()

City
Nairobi    34
Kampala    30
Kigali     23
Arusha     20
Lusaka     16
Name: count, dtype: int64

In [35]:
#Forward fill and backward fill mainly timeseries
#FFILL on Name column
employees_clear["Name"].fillna(method= 'ffill', inplace= True)

/var/folders/cd/723sy5ds4zb86dp0jtwmyl680000gn/T/ipykernel_53566/4002489132.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  employees_clear["Name"].fillna(method= 'ffill', inplace= True)

In [36]:
employees_clear.isnull().sum()

ID              0
Name            0
Age             0
Department      1
Salary          0
City            0
Final Salary    0
Ratio           0
dtype: int64

In [37]:
#Forward fill and backward fill mainly timeseries
#BFILL on department column
employees_clear["Department"].fillna(method= 'bfill', inplace= True)

/var/folders/cd/723sy5ds4zb86dp0jtwmyl680000gn/T/ipykernel_53566/1993347359.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  employees_clear["Department"].fillna(method= 'bfill', inplace= True)

In [38]:
employees_clear.isnull().sum()

ID              0
Name            0
Age             0
Department      0
Salary          0
City            0
Final Salary    0
Ratio           0
dtype: int64

## Duplicates Values

In [40]:
# Duplication from the dataframe
employees_clear.duplicated().sum()

3

In [41]:
## Droping the duplicates values
employees_clear_no_duplicates = employees_clear.drop_duplicates()

In [42]:
employees_clear_no_duplicates.duplicated().sum()

0

In [43]:
employees_clear_no_duplicates.shape

(120, 8)

In [ ]:
## Droping the duplicates values with subset of name and age
employees_clear_no_duplicates = employees_clear.drop_duplicates(subset= ["Name", "Age"])

In [44]:
#Duplicated rows with subset
employees_clear.duplicated(subset= ["Name"]).sum()

113

In [45]:
employees_clear["Name"].value_counts()

Name
Fatima     19
Charlie    14
Diana      14
George     12
Bob        12
Helen      11
Ian        11
Eric       11
Alice      10
Jane        9
Name: count, dtype: int64

In [46]:
## Droping the duplicates values with subset of name and age and first or last
employees_clear_no_duplicates = employees_clear.drop_duplicates(subset= ["Name", "Age"], keep= 'last')

In [47]:
## Checking the number of unique values on a column
employees_clear["Department"].nunique()

5

In [51]:
# Renaming the column
employees_clear = employees_clear.rename(columns= {"Final Salary" : "Final"})

#Displaying the columns of a dataframe
employees_clear.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary', 'City', 'Final', 'Ratio'], dtype='object')

## Sorting a dataframe

In [14]:
#Sorting values by default uses ascending from small to high by age
employees.sort_values(by = ["Age"]).head(30)

      ID     Name   Age  Department  Salary     City
122  111    Helen  22.0          IT   68356  Nairobi
54    55    Diana  22.0          IT   44591   Arusha
51    52     Eric  22.0          IT   80829  Nairobi
42    43      Bob  22.0          IT   72869   Kigali
110  111    Helen  22.0          IT   68356  Nairobi
31    32    Diana  23.0  Operations   81395  Nairobi
106  107  Charlie  23.0  Operations   63971   Lusaka
33    34   Fatima  23.0          HR   65456   Lusaka
91    92   George  24.0          HR   85566   Lusaka
20    21   George  24.0          HR   44897   Kigali
70    71     Eric  25.0          HR   77268   Arusha
39    40    Helen  25.0   Marketing   74831  Kampala
118  119    Helen  25.0  Operations   67811   Kigali
121  110     Eric  26.0          HR   68833  Nairobi
109  110     Eric  26.0          HR   68833  Nairobi
77    78     Eric  26.0          HR   71485   Lusaka
30    31     Jane  26.0  Operations   41451  Kampala
88    89   Fatima  28.0   Marketing   48182   Lusaka
93    94    Diana  28.0   Marketing   79406  Kampala
59    60   Fatima  28.0  Operations   63941   Arusha
23    24    Diana  29.0  Operations   50425  Nairobi
75    76    Alice  29.0  Operations   54428   Arusha
11    12    Helen  29.0          HR   45098   Arusha
105  106      Bob  30.0   Marketing   75886  Nairobi
15    16    Alice  30.0          IT   64696   Arusha
5      6    Alice  30.0   Marketing   70833  Nairobi
92    93  Charlie  31.0          IT   82236   Kigali
25    26   Fatima  31.0          HR   41847   Kigali
10    11  Charlie  31.0  Operations   77178   Kigali
18    19    Alice  31.0  Operations   72722  Kampala

In [16]:
#Sorting values by descending from high to smallest by age
employees.sort_values(by = ["Age"], ascending = False).head(15)

      ID     Name   Age  Department  Salary     City
67    68     Eric  55.0     Finance   54622  Nairobi
113  114      NaN  55.0          HR   56460  Kampala
112  113      Bob  55.0          IT   62140  Nairobi
99   100    Helen  54.0          IT   61349   Kigali
117  118    Diana  54.0     Finance   44606   Arusha
65    66   George  54.0  Operations   63471  Nairobi
82    83  Charlie  53.0  Operations   57285   Arusha
53    54   Fatima  52.0   Marketing   42251  Kampala
4      5      Ian  52.0     Finance   83569  Kampala
41    42    Diana  52.0          HR   86572   Kigali
9     10  Charlie  52.0     Finance   62632   Arusha
1      2  Charlie  51.0          IT   86050  Kampala
57    58     Eric  51.0          HR   79491  Kampala
115  116     Eric  51.0     Finance   44349      NaN
72    73      Bob  51.0   Marketing   86036   Kigali

In [23]:
## Sorting with multiple columns
employees.sort_values(by = ["Age", "City"], ascending = [False, False]).head(25)

      ID     Name   Age  Department  Salary     City
67    68     Eric  55.0     Finance   54622  Nairobi
112  113      Bob  55.0          IT   62140  Nairobi
113  114      NaN  55.0          HR   56460  Kampala
65    66   George  54.0  Operations   63471  Nairobi
99   100    Helen  54.0          IT   61349   Kigali
117  118    Diana  54.0     Finance   44606   Arusha
82    83  Charlie  53.0  Operations   57285   Arusha
41    42    Diana  52.0          HR   86572   Kigali
4      5      Ian  52.0     Finance   83569  Kampala
53    54   Fatima  52.0   Marketing   42251  Kampala
9     10  Charlie  52.0     Finance   62632   Arusha
81    82  Charlie  51.0          IT   57459  Nairobi
68    69      Bob  51.0   Marketing   48946   Lusaka
72    73      Bob  51.0   Marketing   86036   Kigali
1      2  Charlie  51.0          IT   86050  Kampala
57    58     Eric  51.0          HR   79491  Kampala
115  116     Eric  51.0     Finance   44349      NaN
74    75      Ian  50.0   Marketing   81351  Nairobi
60    61     Jane  50.0   Marketing   85880   Lusaka
107  108      Ian  50.0          HR   82014   Lusaka
27    28      Ian  50.0          HR   87007   Kigali
46    47     Jane  50.0     Finance   77914   Kigali
19    20    Diana  50.0  Operations   49651  Kampala
89    90   George  50.0   Marketing   78210   Arusha
83    84    Diana  49.0         NaN   85582  Kampala

In [25]:
## Sorting with multiple columns and keep missing on top or first
employees.sort_values(by = ["Age", "City"], ascending = [False, False], na_position= 'first').head(25)

      ID     Name   Age  Department  Salary     City
8      9   George   NaN     Finance   89566  Nairobi
16    17    Helen   NaN   Marketing   62319   Lusaka
67    68     Eric  55.0     Finance   54622  Nairobi
112  113      Bob  55.0          IT   62140  Nairobi
113  114      NaN  55.0          HR   56460  Kampala
65    66   George  54.0  Operations   63471  Nairobi
99   100    Helen  54.0          IT   61349   Kigali
117  118    Diana  54.0     Finance   44606   Arusha
82    83  Charlie  53.0  Operations   57285   Arusha
41    42    Diana  52.0          HR   86572   Kigali
4      5      Ian  52.0     Finance   83569  Kampala
53    54   Fatima  52.0   Marketing   42251  Kampala
9     10  Charlie  52.0     Finance   62632   Arusha
115  116     Eric  51.0     Finance   44349      NaN
81    82  Charlie  51.0          IT   57459  Nairobi
68    69      Bob  51.0   Marketing   48946   Lusaka
72    73      Bob  51.0   Marketing   86036   Kigali
1      2  Charlie  51.0          IT   86050  Kampala
57    58     Eric  51.0          HR   79491  Kampala
74    75      Ian  50.0   Marketing   81351  Nairobi
60    61     Jane  50.0   Marketing   85880   Lusaka
107  108      Ian  50.0          HR   82014   Lusaka
27    28      Ian  50.0          HR   87007   Kigali
46    47     Jane  50.0     Finance   77914   Kigali
19    20    Diana  50.0  Operations   49651  Kampala

In [27]:
## Sorting with multiple columns and keep missing on top or first
employees.sort_values(by = ["Age", "Department"], ascending = [False, False]).head(25)

      ID     Name   Age  Department  Salary     City
112  113      Bob  55.0          IT   62140  Nairobi
113  114      NaN  55.0          HR   56460  Kampala
67    68     Eric  55.0     Finance   54622  Nairobi
65    66   George  54.0  Operations   63471  Nairobi
99   100    Helen  54.0          IT   61349   Kigali
117  118    Diana  54.0     Finance   44606   Arusha
82    83  Charlie  53.0  Operations   57285   Arusha
53    54   Fatima  52.0   Marketing   42251  Kampala
41    42    Diana  52.0          HR   86572   Kigali
4      5      Ian  52.0     Finance   83569  Kampala
9     10  Charlie  52.0     Finance   62632   Arusha
68    69      Bob  51.0   Marketing   48946   Lusaka
72    73      Bob  51.0   Marketing   86036   Kigali
1      2  Charlie  51.0          IT   86050  Kampala
81    82  Charlie  51.0          IT   57459  Nairobi
57    58     Eric  51.0          HR   79491  Kampala
115  116     Eric  51.0     Finance   44349      NaN
19    20    Diana  50.0  Operations   49651  Kampala
60    61     Jane  50.0   Marketing   85880   Lusaka
74    75      Ian  50.0   Marketing   81351  Nairobi
89    90   George  50.0   Marketing   78210   Arusha
27    28      Ian  50.0          HR   87007   Kigali
107  108      Ian  50.0          HR   82014   Lusaka
46    47     Jane  50.0     Finance   77914   Kigali
83    84    Diana  49.0         NaN   85582  Kampala

## Replacing values from dataframe

In [28]:
## Transform text or string format on dataframe to small letter
employees["City"] = employees["City"].str.lower()
employees.head(17)

    ID     Name   Age  Department  Salary     City
0    1    Helen  47.0   Marketing   71631  kampala
1    2  Charlie  51.0          IT   86050  kampala
2    3   Fatima  47.0  Operations   89827  kampala
3    4   Fatima  36.0          IT   72871   arusha
4    5      Ian  52.0     Finance   83569  kampala
5    6    Alice  30.0   Marketing   70833  nairobi
6    7   George  38.0          HR   58860   lusaka
7    8     Jane  31.0  Operations   60921   arusha
8    9   George   NaN     Finance   89566  nairobi
9   10  Charlie  52.0     Finance   62632   arusha
10  11  Charlie  31.0  Operations   77178   kigali
11  12    Helen  29.0          HR   45098   arusha
12  13  Charlie  39.0  Operations   88244  nairobi
13  14      Bob  44.0  Operations   77064   arusha
14  15   Fatima  43.0  Operations   45364   arusha
15  16    Alice  30.0          IT   64696   arusha
16  17    Helen   NaN   Marketing   62319   lusaka

In [36]:
## Transform text or string format on dataframe to capital letter
employees["Name"] = employees["Name"].str.upper()
employees.head(17)

    ID     Name   Age  Department  Salary         City
0    1    HELEN  47.0   Marketing   71631  Addis Abeba
1    2  CHARLIE  51.0          IT   86050      Kampala
2    3   FATIMA  47.0  Operations   89827  Addis Abeba
3    4   FATIMA  36.0          IT   72871       Arusha
4    5      IAN  52.0     Finance   83569      Kampala
5    6    ALICE  30.0   Marketing   70833      Nairobi
6    7   GEORGE  38.0          HR   58860       Lusaka
7    8     JANE  31.0  Operations   60921       Arusha
8    9   GEORGE   NaN     Finance   89566      Nairobi
9   10  CHARLIE  52.0     Finance   62632       Arusha
10  11  CHARLIE  31.0  Operations   77178       Kigali
11  12    HELEN  29.0          HR   45098       Arusha
12  13  CHARLIE  39.0  Operations   88244      Nairobi
13  14      BOB  44.0  Operations   77064       Arusha
14  15   FATIMA  43.0  Operations   45364       Arusha
15  16    ALICE  30.0          IT   64696       Arusha
16  17    HELEN   NaN   Marketing   62319       Lusaka

In [33]:
#Changing the dataframe value using iloc and loc
employees.iloc[2, 5] = 'addis abeba'
employees.head(5)

   ID     Name   Age  Department  Salary         City
0   1    HELEN  47.0   Marketing   71631  addis abeba
1   2  CHARLIE  51.0          IT   86050      kampala
2   3   FATIMA  47.0  Operations   89827  addis abeba
3   4   FATIMA  36.0          IT   72871       arusha
4   5      IAN  52.0     Finance   83569      kampala

In [35]:
## Transform text or string format on dataframe to capital letter on first character
employees["City"] = employees["City"].str.title()
employees.head(17)

    ID     Name   Age  Department  Salary         City
0    1    HELEN  47.0   Marketing   71631  Addis Abeba
1    2  CHARLIE  51.0          IT   86050      Kampala
2    3   FATIMA  47.0  Operations   89827  Addis Abeba
3    4   FATIMA  36.0          IT   72871       Arusha
4    5      IAN  52.0     Finance   83569      Kampala
5    6    ALICE  30.0   Marketing   70833      Nairobi
6    7   GEORGE  38.0          HR   58860       Lusaka
7    8     JANE  31.0  Operations   60921       Arusha
8    9   GEORGE   NaN     Finance   89566      Nairobi
9   10  CHARLIE  52.0     Finance   62632       Arusha
10  11  CHARLIE  31.0  Operations   77178       Kigali
11  12    HELEN  29.0          HR   45098       Arusha
12  13  CHARLIE  39.0  Operations   88244      Nairobi
13  14      BOB  44.0  Operations   77064       Arusha
14  15   FATIMA  43.0  Operations   45364       Arusha
15  16    ALICE  30.0          IT   64696       Arusha
16  17    HELEN   NaN   Marketing   62319       Lusaka

In [37]:
## Transform text or string format on dataframe to capital letter on first character on whole word
employees["City"] = employees["City"].str.capitalize()
employees.head(17)

    ID     Name   Age  Department  Salary         City
0    1    HELEN  47.0   Marketing   71631  Addis abeba
1    2  CHARLIE  51.0          IT   86050      Kampala
2    3   FATIMA  47.0  Operations   89827  Addis abeba
3    4   FATIMA  36.0          IT   72871       Arusha
4    5      IAN  52.0     Finance   83569      Kampala
5    6    ALICE  30.0   Marketing   70833      Nairobi
6    7   GEORGE  38.0          HR   58860       Lusaka
7    8     JANE  31.0  Operations   60921       Arusha
8    9   GEORGE   NaN     Finance   89566      Nairobi
9   10  CHARLIE  52.0     Finance   62632       Arusha
10  11  CHARLIE  31.0  Operations   77178       Kigali
11  12    HELEN  29.0          HR   45098       Arusha
12  13  CHARLIE  39.0  Operations   88244      Nairobi
13  14      BOB  44.0  Operations   77064       Arusha
14  15   FATIMA  43.0  Operations   45364       Arusha
15  16    ALICE  30.0          IT   64696       Arusha
16  17    HELEN   NaN   Marketing   62319       Lusaka

In [38]:
## Replacing the values from Arusha to Dodoma
employees["City"]  = employees["City"].replace("Arusha", "Dodoma")
employees.head(15)

    ID     Name   Age  Department  Salary         City
0    1    HELEN  47.0   Marketing   71631  Addis abeba
1    2  CHARLIE  51.0          IT   86050      Kampala
2    3   FATIMA  47.0  Operations   89827  Addis abeba
3    4   FATIMA  36.0          IT   72871       Dodoma
4    5      IAN  52.0     Finance   83569      Kampala
5    6    ALICE  30.0   Marketing   70833      Nairobi
6    7   GEORGE  38.0          HR   58860       Lusaka
7    8     JANE  31.0  Operations   60921       Dodoma
8    9   GEORGE   NaN     Finance   89566      Nairobi
9   10  CHARLIE  52.0     Finance   62632       Dodoma
10  11  CHARLIE  31.0  Operations   77178       Kigali
11  12    HELEN  29.0          HR   45098       Dodoma
12  13  CHARLIE  39.0  Operations   88244      Nairobi
13  14      BOB  44.0  Operations   77064       Dodoma
14  15   FATIMA  43.0  Operations   45364       Dodoma

In [39]:
## Replacing the values from Arusha to Dodoma and also Nairobi to Mombasa
employees["City"]  = employees["City"].replace({
    "Arusha" : "Dodomo",
    "Nairobi" : "Mombasa",
    "Kigali" : "Kigali City"
})
employees.head(15)

    ID     Name   Age  Department  Salary         City
0    1    HELEN  47.0   Marketing   71631  Addis abeba
1    2  CHARLIE  51.0          IT   86050      Kampala
2    3   FATIMA  47.0  Operations   89827  Addis abeba
3    4   FATIMA  36.0          IT   72871       Dodoma
4    5      IAN  52.0     Finance   83569      Kampala
5    6    ALICE  30.0   Marketing   70833      Mombasa
6    7   GEORGE  38.0          HR   58860       Lusaka
7    8     JANE  31.0  Operations   60921       Dodoma
8    9   GEORGE   NaN     Finance   89566      Mombasa
9   10  CHARLIE  52.0     Finance   62632       Dodoma
10  11  CHARLIE  31.0  Operations   77178  Kigali City
11  12    HELEN  29.0          HR   45098       Dodoma
12  13  CHARLIE  39.0  Operations   88244      Mombasa
13  14      BOB  44.0  Operations   77064       Dodoma
14  15   FATIMA  43.0  Operations   45364       Dodoma

In [40]:
employees["City"].unique()

array(['Addis abeba', 'Kampala', 'Dodoma', 'Mombasa', 'Lusaka',
       'Kigali City', nan], dtype=object)

## Grouping a dataframe
Used aggragation funtions (sum, mean, min, max, median, count, mode, variance)

In [41]:
## Grouping total salaries by department
employees.groupby("Department")["Salary"].sum()

Department
Finance        982604
HR            2111879
IT            1760696
Marketing     1567656
Operations    1774198
Name: Salary, dtype: int64

In [42]:
## Grouping average salaries by department
employees.groupby("Department")["Salary"].mean()

Department
Finance       65506.933333
HR            68125.129032
IT            67719.076923
Marketing     71257.090909
Operations    63364.214286
Name: Salary, dtype: float64

In [48]:
## Counting the number of the values from a column
employees["Department"].value_counts()

Department
HR            31
Operations    28
IT            26
Marketing     22
Finance       15
Name: count, dtype: int64

In [50]:
## Grouping with more than one columns Department and City
employees.groupby(["Department", "City"])["Salary"].sum()

Department  City
Finance     Dodoma         164703
            Kampala        157971
            Kigali City    163597
            Lusaka          85319
            Mombasa        366665
HR          Dodoma         177547
            Kampala        487491
            Kigali City    520932
            Lusaka         489328
            Mombasa        436581
IT          Dodoma         238754
            Kampala        291939
            Kigali City    457626
            Lusaka          74939
            Mombasa        608886
Marketing   Addis abeba     71631
            Dodoma         209117
            Kampala        360933
            Kigali City    216297
            Lusaka         329079
            Mombasa        380599
Operations  Addis abeba     89827
            Dodoma         424717
            Kampala        532999
            Kigali City    201971
            Lusaka         127059
            Mombasa        335303
Name: Salary, dtype: int64

In [53]:
## Grouping with more than one columns Department and City by ingoring the indexes
#Get the result as a table using reset_index()
employees.groupby(["Department", "City"])["Salary"].sum().reset_index()

    Department         City  Salary
0      Finance       Dodoma  164703
1      Finance      Kampala  157971
2      Finance  Kigali City  163597
3      Finance       Lusaka   85319
4      Finance      Mombasa  366665
5           HR       Dodoma  177547
6           HR      Kampala  487491
7           HR  Kigali City  520932
8           HR       Lusaka  489328
9           HR      Mombasa  436581
10          IT       Dodoma  238754
11          IT      Kampala  291939
12          IT  Kigali City  457626
13          IT       Lusaka   74939
14          IT      Mombasa  608886
15   Marketing  Addis abeba   71631
16   Marketing       Dodoma  209117
17   Marketing      Kampala  360933
18   Marketing  Kigali City  216297
19   Marketing       Lusaka  329079
20   Marketing      Mombasa  380599
21  Operations  Addis abeba   89827
22  Operations       Dodoma  424717
23  Operations      Kampala  532999
24  Operations  Kigali City  201971
25  Operations       Lusaka  127059
26  Operations      Mombasa  335303

In [55]:
## More than one aggragation functions on several columns at once
employees.groupby("City").agg({"Salary": ["mean", "max", "min"],
                              "Age": ["mean", "median"]})

                   Salary                      Age
                     mean    max    min       mean median
City
Addis abeba  80729.000000  89827  71631  47.000000   47.0
Dodoma       60741.900000  81050  44591  38.600000   39.5
Kampala      68461.250000  87593  40451  41.357143   40.5
Kigali City  67844.478261  88383  41455  38.826087   37.0
Lusaka       69107.750000  85880  48182  35.533333   35.0
Mombasa      68646.258065  89566  49365  36.866667   34.5

## Pivotting of Dataframe

In [2]:
def withdraw(balance, amount):
    try:
        if amount > balance:
            raise ValueError("Insufficient funds")
        balance -= amount
        return balance
    except ValueError as e:
        return f"Transaction failed: {e}"

print(withdraw(1000, 200))   # 800
print(withdraw(1000, 2000))  # Transaction failed: Insufficient funds

800
Transaction failed: Insufficient funds

In [116]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [124]:
8%5

2

In [4]:

n = 5
fact = 1
for i in range(1,n+1):
    fact *=i
print(fact)

120

In [206]:
#When the flow is dependent
category = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]
for x in category:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

In [207]:
#Printing charactors of a stringas a whole
for t in "Ishimwe":
    print(t)

I
s
h
i
m
w
e

## Creating a dictionary

In [36]:
dict1 = {
    "name" : ["Eric", "Egide"],
    "age": [25, 30]
}

In [48]:
dict1.items()

dict_items([('name', ['Eric', 'Egide']), ('age', [25, 30])])

In [3]:
age.pop(2)

34

In [4]:
age

[30, 29, 35, 36, 27, 25, 29, 28, 30, 30]

In [7]:
age.count(30)

3

In [10]:
# Used to insert a values in the existing list
age.insert(2, 33)

In [11]:
print(age)

[30, 29, 33, 33, 35, 36, 27, 25, 29, 28, 30, 30]

In [14]:
age.append([39, 37, 36])

In [16]:
age.index(27)

6

In [17]:
age.remove(33)

In [19]:
age.reverse()

In [ ]:
age.pop(0))

In [27]:
age.sort(reverse= True)

In [29]:
age.clear()

In [30]:
print(age)

[]

### One Value to Multiple Variables
And you can assign the same value to multiple variables in one line:

In [4]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange

## Python - Output Variables
*Output Variables:*
The Python _print()_ function is often used to output variables.

In [7]:
x = "Python is awesome"
print(x)

Python is awesome

In [8]:
# In the print() function, you output multiple variables, separated by a comma:
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

Python is awesome

In [13]:
# You can also use the + operator to output multiple variables:
x = "Python "
y = "is "
z = "awesome"
print(x + y + z)

# Notice the space character after "Python " and "is ", without them the result would be "Pythonisawesome".

Python is awesome

In [14]:
# For numbers, the + character works as a mathematical operator:
x = 5
y = 10
print(x + y)

15

In [ ]:
# In the print() function, when you try to combine a string and a number with the + operator, Python will give you an error:
x = 5
y = "John"
print(x + y)
#You can't add integer to a string data type, but float, complex and integer can be added

In [19]:
""" The best way to output multiple variables in the print() function is to separate them with commas,
which even support different data types:"""
x = 5
y = "John"
print(x, y)

5 John

## Using Variables within Print Function

In [8]:
name = "Emmanuel"
age = 32
print(f"Dear {name}, you are {age} years old")

Dear Emmanuel, you are 32 years old

In [9]:
print("Dear {} you are {} years old".format(name,age))

Dear Emmanuel you are 32 years old

In [10]:
print("Dear %s you are %d years old" % (name, age))

Dear Emmanuel you are 32 years old

In [12]:
name = input("Your name: ")
age = int(input("Your age: "))
print(f"Hello {name}, you will be {age + 1} next year!")

Your name:  Eric
Your age:  32

Hello Eric, you will be 33 next year!

## Exercise for Previous Class

In [ ]:
#1. Create a variable named x and assign the value 50 to it.

In [21]:
#2. Create a variable named carname and assign the value Volvo to it.

In [ ]:
#3. Which is invalid variable name?
my-var = 20
my_var = 20
Myvar = 20
_myvar = 20

In [ ]:
# 4. What will be the result of the following code:
x = 'Welcome'
print(x[3:5])

In [25]:
# 5. Get the characters from index 2 to index 4 (llo).
txt = "Hello World"
x = txt[2:5]
print(x)

llo

In [ ]:
# 6. What will be the result of the following code:
x = 'Welcome'
print(x[3:])

In [ ]:
#7. Select the correct functions to print the data type of a variable:
myvar = 3.5
---(---(myvar))